import { TemplateDefinition } from '../types.js';

export const ChambersTemplate: TemplateDefinition = {
  id: 'chambers-2024',
  name: 'Chambers Submission',
  type: 'chambers',
  description: 'Template for Chambers and Partners submission',
  outputFormat: 'xlsx',
  version: '2024',
  fields: [
    {
      name: 'submittingFirm',
      label: 'Submitting Firm',
      type: 'text',
      required: true,
    },
    {
      name: 'practiceGroup',
      label: 'Practice Group',
      type: 'select',
      required: true,
      options: [
        'Corporate/M&A',
        'Banking & Finance',
        'Capital Markets',
        'Dispute Resolution',
        'Real Estate',
        'Tax',
        'Restructuring/Insolvency',
        'Private Equity',
      ],
    },
    {
      name: 'matterName',
      label: 'Matter Name',
      type: 'text',
      required: true,
      mappedFrom: 'title',
    },
    {
      name: 'client',
      label: 'Client',
      type: 'text',
      required: true,
      mappedFrom: 'clientName',
    },
    {
      name: 'matterValue',
      label: 'Matter Value (USD)',
      type: 'number',
      required: false,
      mappedFrom: 'dealValue.amount',
    },
    {
      name: 'synopsis',
      label: 'Synopsis',
      type: 'textarea',
      required: true,
      maxLength: 3000,
      mappedFrom: 'synthesizedData.description',
    },
    {
      name: 'significance',
      label: 'Significance',
      type: 'textarea',
      required: true,
      maxLength: 1000,
      mappedFrom: 'synthesizedData.legalNovelty',
    },
    {
      name: 'keyPartner',
      label: 'Key Partner',
      type: 'text',
      required: true,
      mappedFrom: 'leadPartner',
    },
    {
      name: 'otherLawyers',
      label: 'Other Key Lawyers',
      type: 'textarea',
      required: false,
      mappedFrom: 'teamMembers',
    },
    {
      name: 'jurisdictions',
      label: 'Jurisdictions',
      type: 'text',
      required: true,
    },
    {
      name: 'dateCompleted',
      label: 'Date Completed',
      type: 'date',
      required: true,
    },
  ],
};
