import { TemplateDefinition } from '../types.js';

export const Duns100Template: TemplateDefinition = {
  id: 'duns100-2024',
  name: "Dun's 100 Submission",
  type: 'duns_100',
  description: "Template for Dun's 100 legal directory submission",
  outputFormat: 'docx',
  version: '2024',
  fields: [
    {
      name: 'firmName',
      label: 'Firm Name',
      type: 'text',
      required: true,
      maxLength: 200,
    },
    {
      name: 'practiceArea',
      label: 'Practice Area',
      type: 'select',
      required: true,
      options: [
        'M&A',
        'Corporate',
        'Litigation',
        'Banking & Finance',
        'Real Estate',
        'Intellectual Property',
        'Employment',
        'Tax',
      ],
    },
    {
      name: 'matterTitle',
      label: 'Matter Title',
      type: 'text',
      required: true,
      maxLength: 500,
      mappedFrom: 'title',
    },
    {
      name: 'clientName',
      label: 'Client Name',
      type: 'text',
      required: true,
      maxLength: 200,
      mappedFrom: 'clientName',
    },
    {
      name: 'counterparties',
      label: 'Counterparties',
      type: 'textarea',
      required: false,
      mappedFrom: 'counterparties',
    },
    {
      name: 'dealValue',
      label: 'Deal Value',
      type: 'text',
      required: false,
      mappedFrom: 'dealValue.amount',
    },
    {
      name: 'description',
      label: 'Matter Description',
      type: 'textarea',
      required: true,
      maxLength: 2000,
      mappedFrom: 'synthesizedData.description',
    },
    {
      name: 'keyAchievements',
      label: 'Key Achievements',
      type: 'textarea',
      required: false,
      mappedFrom: 'synthesizedData.keyAchievements',
    },
    {
      name: 'leadPartnerName',
      label: 'Lead Partner',
      type: 'text',
      required: true,
      mappedFrom: 'leadPartner',
    },
    {
      name: 'teamMembers',
      label: 'Team Members',
      type: 'textarea',
      required: false,
      mappedFrom: 'teamMembers',
    },
    {
      name: 'completionDate',
      label: 'Completion Date',
      type: 'date',
      required: true,
    },
  ],
};
