import { TemplateDefinition } from '../types.js';

export const Legal500Template: TemplateDefinition = {
  id: 'legal500-2024',
  name: 'Legal 500 Submission',
  type: 'legal_500',
  description: 'Template for Legal 500 directory submission',
  outputFormat: 'docx',
  version: '2024',
  fields: [
    {
      name: 'firmName',
      label: 'Firm Name',
      type: 'text',
      required: true,
      maxLength: 200,
    },
    {
      name: 'practiceArea',
      label: 'Practice Area',
      type: 'select',
      required: true,
      options: [
        'Commercial, Corporate and M&A',
        'Banking and Finance',
        'Capital Markets',
        'Dispute Resolution',
        'Employment',
        'Intellectual Property',
        'Real Estate',
        'Restructuring and Insolvency',
        'Tax',
        'TMT',
        'Transport',
        'Private Client',
      ],
    },
    {
      name: 'matterTitle',
      label: 'Work Highlight Title',
      type: 'text',
      required: true,
      maxLength: 300,
      mappedFrom: 'title',
    },
    {
      name: 'clientName',
      label: 'Client',
      type: 'text',
      required: true,
      maxLength: 200,
      mappedFrom: 'clientName',
    },
    {
      name: 'counterparties',
      label: 'Other Parties',
      type: 'textarea',
      required: false,
      mappedFrom: 'counterparties',
    },
    {
      name: 'dealValue',
      label: 'Deal/Matter Value',
      type: 'text',
      required: false,
      mappedFrom: 'dealValue.amount',
    },
    {
      name: 'currency',
      label: 'Currency',
      type: 'select',
      required: false,
      options: ['USD', 'EUR', 'GBP', 'ILS', 'Other'],
      mappedFrom: 'dealValue.currency',
    },
    {
      name: 'workHighlight',
      label: 'Work Highlight Description',
      type: 'textarea',
      required: true,
      maxLength: 1500,
      mappedFrom: 'synthesizedData.description',
    },
    {
      name: 'significance',
      label: 'Why is this work significant?',
      type: 'textarea',
      required: true,
      maxLength: 500,
      mappedFrom: 'synthesizedData.legalNovelty',
    },
    {
      name: 'innovation',
      label: 'Innovative aspects',
      type: 'textarea',
      required: false,
      maxLength: 500,
    },
    {
      name: 'outcome',
      label: 'Outcome achieved',
      type: 'textarea',
      required: true,
      maxLength: 500,
    },
    {
      name: 'leadPartner',
      label: 'Lead Partner(s)',
      type: 'text',
      required: true,
      mappedFrom: 'leadPartner',
    },
    {
      name: 'keyLawyers',
      label: 'Key Fee Earners',
      type: 'textarea',
      required: false,
      mappedFrom: 'teamMembers',
    },
    {
      name: 'startDate',
      label: 'Start Date',
      type: 'date',
      required: false,
    },
    {
      name: 'completionDate',
      label: 'Completion Date',
      type: 'date',
      required: true,
    },
    {
      name: 'ongoing',
      label: 'Ongoing Matter?',
      type: 'select',
      required: true,
      options: ['Yes', 'No'],
    },
    {
      name: 'crossBorder',
      label: 'Cross-border elements?',
      type: 'select',
      required: true,
      options: ['Yes', 'No'],
    },
    {
      name: 'jurisdictions',
      label: 'Jurisdictions involved',
      type: 'textarea',
      required: false,
    },
  ],
};
